apiVersion: v1
kind: Service
metadata:
  name: flower-nginx
  labels:
    app: flower
spec:
  clusterIP: None
  selector:
    app: flower
  ports:
    - protocol: TCP
      port: 8000
      name: http
      targetPort: 8000
  ports:
    - protocol: TCP
      port: 8001
      name: grpc
      targetPort: 8001
