apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxplus-rc
spec:
  replicas: 1
  selector:
    app: nginxplus
  template:
    metadata:
      labels:
        app: nginxplus
    spec:
      nodeSelector:
        role: nginxplus
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nginxplus
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "nginx; while true; do sleep 30; done;" ]
        imagePullPolicy: IfNotPresent
        image: nvcr.io/nvidian/swdl/nginxplus:v1
        ports:
          - name: http
            containerPort: 80
            hostPort: 8085
          - name: grpc
            containerPort: 89
            hostPort: 8087
          - name: http-alt
            containerPort: 8080
            hostPort: 8086
          - name: flower-svc
            containerPort: 8000
            hostPort: 32309
        volumeMounts:
          - mountPath: "/etc/nginx/conf.d"
            name: etc-nginx-confd
      volumes:
        - nfs:
           server: 192.168.20.80
           path: /volume1/NFSVolume/flowerdemo/nginx/conf.d
           readOnly: false
          name: etc-nginx-confd
